### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by ryanwalexander** [jrfernandes/ontario_energy_board#27]
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/ontario_energy_board/__init__.py:21
Integration: Ontario Energy Board (documentation, issues)
First occurred: May 6, 2023 at 9:48:22 PM (2 occurrences)
Last logged: 9:09:09 PM

Error setting up entry Toronto Hydro-Electric System Limited (RESIDENTIAL) for ontario_energy_board
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/ontario_energy_board/__init__.py", line 21, in async_setup_entry
    hass.config_entries.async_setup_platforms(entry, PLATFORMS)
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by tmur11** [comment]
Also not workng for me over here either. Same error

**Comment by tmur11** [comment]
@ryanwalexander should be an update available under HACS menu.

![image](https://github.com/jrfernandes/ontario_energy_board/assets/21132832/7d344b09-8efb-45c9-b46c-389488388bf4)

**Comment by ryanwalexander** [comment]
Thanks!
