### ISSUE TITLE
Ontario Energy Board was working fine yesterday....

### ISSUE THREAD

**Issue by kwkid** [jrfernandes/ontario_energy_board#3]
Installed from HACS yesterday, added via the UI and configure with my local Electrical Distributor...Rates came in and things were looking promising...

Today no so good...The sensor's state for the electrical distributor shows unavailable whereas yesterday it was the $ rate and was working thru the on peak, mid peak and off peak tiers....

here's the error i am getting..

**** start *******
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 530, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 563, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 536, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 371, in state
value = self.native_value
File "/config/custom_components/ontario_energy_board/sensor.py", line 35, in native_value
return self.coordinator.ontario_energy_board.active_peak_rate
File "/config/custom_components/ontario_energy_board/api.py", line 113, in active_peak_rate
return getattr(self, f"{self.active_peak}_rate")
AttributeError: 'OntarioEnergyBoard' object has no attribute 'None_rate'
2022-02-08 12:51:18 ERROR (MainThread) [custom_components.ontario_energy_board.api] Could not find active peak. Perhaps the webpage layout has changed
2022-02-08 12:51:18 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
****** end *********

I tried uninstalling, rebooting and the re-installing rebooting to no avail...just installed 

version: core-2022.2.3
installation_type: Home Assistant OS
host_os: Home Assistant OS 7.2
supervisor_version: supervisor-2022.01.1

**Comment by jrfernandes** [comment]
Unfortunately, it appears that that the OEB site no longer includes a page indicating the current peak. That didn't last long :/

The rates are still being pulled successfully, as it's part of their Open Data initiative. As for getting the current rate, we will need a new method to get that. I might take a shot at it during the weekend.

**Comment by jrfernandes** [comment]
Thank you for reporting this. As mentioned in #3, it looks like the OEB removed the page that indicated the current rate. We'll need a new method to get the current rate.
