### ISSUE TITLE
Errors after upgrading to HASS 2024.4.4

### ISSUE THREAD

**Issue by sirtow** [jrfernandes/ontario_energy_board#48]
Getting the error below for `Alectra Utilities Corporation-PowerStream Rate Zone (RESIDENTIAL)`
``` 
Traceback (most recent call last):
   File "/srv/homeassistant/lib/python3.12/site-packages/homeassistant/helpers/update_coordinator.py", line 315, in _async_refresh
     self.data = await self._async_update_data()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/home/ha/.homeassistant/custom_components/ontario_energy_board/coordinator.py", line 57, in _async_update_data
     company_energy_sector_search.group(1).lower().replace(" ", "_")
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by jrfernandes** [comment]
Are you using the latest version ([v0.4.1](https://github.com/jrfernandes/ontario_energy_board/releases/tag/v0.4.1))?
