### ISSUE TITLE
Unable To Install Integration - Error Fetching Data

### ISSUE THREAD

**Issue by BeyondCurious** [jrfernandes/ontario_energy_board#56]
Integration fails to load.  "Failed setup, will retry; mismatched tag: line 1, column 38229"

Log shows:

`2024-08-14 14:32:31.259 ERROR (MainThread) [custom_components.ontario_energy_board.coordinator] Unexpected error fetching ontario_energy_board data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ontario_energy_board/coordinator.py", line 59, in _async_update_data
    self.company_data = await get_energy_company_data(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ontario_energy_board/common.py", line 104, in get_energy_company_data
    tree = ET.fromstring(content)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/xml/etree/ElementTree.py", line 1335, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 1, column 38229`

*****EDIT:**  I was using the Toronto Residential provider like others previously reporting a similar problem. I deleted it and tried to add a different provider but now I get: 

**### "Error Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble".** 

**My setup**:

Haces Integration version:	1.34.0
Hacs Frontend version:	20220906112053

Home Assistant Core:   2024.8.1
Home Assistant Supervisor:   2024.08.0
Operating System Frontend:   20240809.0

**Comment by BeyondCurious** [comment]
Closing case I am now able to configure the installation successfully.
