### ISSUE TITLE
Detected blocking call to import_module with args ('holidays.countries.canada',) inside the event loop by custom integration 'ontario_energy_board'

### ISSUE THREAD

**Issue by sn4201** [jrfernandes/ontario_energy_board#59]
```
Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 9:45:16 PM (1 occurrences)
Last logged: 9:45:16 PM

Detected blocking call to import_module with args ('holidays.countries.canada',) inside the event loop by custom integration 'ontario_energy_board' at custom_components/ontario_energy_board/coordinator.py, line 42: self.ontario_holidays = holidays.Canada(prov="ON", observed=True) (offender: /usr/local/lib/python3.12/site-packages/holidays/registry.py, line 244: self.entity = getattr(importlib.import_module(self.module_name), self.entity_name)), please create a bug report at https://github.com/jrfernandes/ontario_energy_board/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component result = await _async_setup_component(hass, domain, config) File "/usr/src/homeassistant/homeassistant/setup.py", line 461, in _async_setup_component await asyncio.gather( File "/usr/src/homeassistant/homeassistant/setup.py", line 463, in <genexpr> create_eager_task( File "/usr/src/homeassistant/homeassistant/util/async_.py", line 45, in create_eager_task return Task(coro, loop=loop, name=name, eager_start=True) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 783, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 546, in async_setup await self.__async_setup_with_context(hass, integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context result = await component.async_setup_entry(hass, self) File "/config/custom_components/ontario_energy_board/__init__.py", line 22, in async_setup_entry coordinator = OntarioEnergyBoardDataUpdateCoordinator(hass) File "/config/custom_components/ontario_energy_board/coordinator.py", line 42, in __init__ self.ontario_holidays = holidays.Canada(prov="ON", observed=True)

```

**Comment by rexbron** [comment]
I also see this error with  HA 2025.1.0b2

**Comment by contactpjb** [comment]
Same here, HA 2025.1, v0.4.1

**Comment by kungfuice** [comment]
Same issue here, HA 2025.1, v0.4.1

**Comment by jeffyjoe** [comment]
The issue is that the integration was calling a blocking function during initialization—in particular, calling holidays.Canada(prov="ON", observed=True) directly in the __init__ method. 
This function internally uses a blocking import (via import_module), which stalls the async event loop in Home Assistant.
In an asynchronous environment, blocking calls must be offloaded to a separate executor so they don't interfere with the rest of the system. this work-around solved it by delaying the call (lazy-loading) and running it with hass.async_add_executor_job.

there is a workaround... up to current 2025.3.3
in the "coordinator.py:" found in the customs dir in /config
open it and find:
`self.ontario_holidays = holidays.Canada(prov="ON", observed=True)`
then replace with:
`if self.ontario_holidays is None:
    self.ontario_holidays = await self.hass.async_add_executor_job(
        holidays.Canada, prov="ON", observed=True
    )`

this should work untill they fix this error
do at your own risk.

**Comment by comet424** [comment]
i having same error with  2025.3.4 core 2025.03.3 supervisor

anything i can do to fix it,?

**Comment by Happy-Cadaver** [comment]
Eureka!

Started following the error into the code which led me to wonder how HA handles holidays, yep it's the [Holiday integration](https://www.home-assistant.io/integrations/holiday). I installed it, rebooted, and warning is gone.

Digging a little further I found that on the day of the OP here [HA 2024.11.3](https://www.home-assistant.io/blog/2024/11/06/release-202411/#2024113---november-22) was released which included a bump in the python holidays library, this must have changed the way it got loaded in the backend.

**Comment by sn4201** [comment]
![Image](https://github.com/user-attachments/assets/33fe6666-800f-4c56-9124-31f86dc9ec69)

This is still occurring for me on latest HA:

``` Core 2025.4.1
Supervisor 2025.03.4
Operating System 15.1
Frontend 20250404.0```

@Happy-Cadaver I tried installing the Holiday integration and rebooting, but it changed nothing.  Was there something else to do to configure it somehow?

**Comment by Happy-Cadaver** [comment]
@sn4201 nope, I too noticed that my solution failed. I did stop it from coming up on every restart but it still throws the warning infrequently. My guess is that the integration is trying to pull the python holiday library before HA has it fully loaded sometimes instead of waiting for it. It's likely a simple fix but I don't speak python :/.

**Comment by comet424** [comment]
i not sure if there be a fix since intergration been broken since christmas or so.. and looks like the programmer last did any updates in october... maybe hes too busy.. or he could be dead.. no idea  since the integration more broken i may have to make entites for the mid off on peaks  and not use  the itegration for the cost values..
