### ISSUE TITLE
Error in latest version of Home Assistant (2024.12.5)

### ISSUE THREAD

**Issue by AdamSutch** [jrfernandes/ontario_energy_board#60]
I think this issue actually started in 2024.12.3 but didn't notice until now.
Running version `v0.4.1`

```
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:960
First occurred: 10:45:51 AM (1306 occurrences)
Last logged: 9:38:23 PM

Update for sensor.hydro_one_networks_inc_r2_residential_electricity_rate fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 960, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1318, in async_device_update
    await self.async_update()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 596, in async_update
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 274, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 114, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 355, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 478, in _async_refresh
    self.async_update_listeners()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 177, in async_update_listeners
    update_callback()
    ~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 558, in _handle_coordinator_update
    self.async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in async_write_ha_state
    self._async_write_ha_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1148, in _async_write_ha_state
    self.__async_calculate_state()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1085, in __async_calculate_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1029, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 557, in state
    value = self.native_value
            ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ontario_energy_board/sensor.py", line 154, in native_value
    if active_peak_mapping is not None and active_peak_mapping in company_data:
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by RicLund** [comment]
Also seeing this issue.

**Comment by deviantintegral** [comment]
I think this is due to a typo in the class name for Hydro One customers. Is anyone else seeing this for other companies?

The key line is:

> 2025-01-01 18:31:57.721 ERROR (MainThread) [custom_components.ontario_energy_board.coordinator] Could not find energy rates for Hydro One Networks Inc. (R1 RESIDENTIAL) [Electricity]

And this causes company data to be set to `None`:

https://github.com/jrfernandes/ontario_energy_board/blob/main/custom_components/ontario_energy_board/coordinator.py#L59-L66

I was able to fix this by deleting the integration configuration, reconfiguring it, and then making sure the entity ID for the sensor matched.

I do think this could be a good place for integrating with Home Assistant's "repairs" system. I don't see anything that says that companies couldn't rename rate classes for legitimate reasons, but as-is the error messages aren't clear.

I've sent this email to `webmaster@oeb.ca`. Hopefully that's the right place!

> Recently I noticed errors in an [open-source tool](https://github.com/jrfernandes/ontario_energy_board/issues/60) home owners can use to manage their electricity use. I think this is due to a change in the data returned by `https://www.oeb.ca/_html/calculator/data/BillData.xml` for Hydro One in the last few weeks.
> 
> Notice how there are two spaces after `R1` and `R2`, instead of just one:
> 
> 
> ```
> 	<BillDataRow>
> 		<Dist>Hydro One Networks Inc.</Dist>
> 		<Class>R1  RESIDENTIAL</Class>
> ```
> 
> And for R2:
> 
> 
> ```
> 	<BillDataRow>
> 		<Dist>Hydro One Networks Inc.</Dist>
> 		<Class>R2  RESIDENTIAL</Class>
> ```
> 
> Normally, if the class changed I think we'd expect users to update their end to work with the new class. But since this appears to be a typo, perhaps it's best changed by Hydro One or whoever manages this?

**Comment by deviantintegral** [comment]
I got a reply that this is now fixed. Can anyone else confirm?

**Comment by RicLund** [comment]
Yes fixed for me after a restart @deviantintegral. Great sleuthing man, thanks!

**Comment by deviantintegral** [comment]
Fixed for me as well! I think this issue can be closed.

**Comment by RicLund** [comment]
@deviantintegral Is yours still working? I'm hitting a new issue that looks to be something similar - a regex not matching in the file. Wonder if something else got changed.

Logger: custom_components.ontario_energy_board.coordinator
Source: helpers/update_coordinator.py:380
integration: Ontario Energy Board ([documentation](https://github.com/jrfernandes/ontario_energy_board), [issues](https://github.com/jrfernandes/ontario_energy_board/issues))
First occurred: 6:00:44 PM (47 occurrences)
Last logged: 6:59:09 PM

Unexpected error fetching ontario_energy_board data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 380, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/ontario_energy_board/coordinator.py", line 56, in _async_update_data
    company_energy_sector_search.group(1).lower().replace(" ", "_")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by deviantintegral** [comment]
I haven't seen any errors in my two installs.

**Comment by deviantintegral** [comment]
I’m now back to seeing errors again. It’s exactly the same issue - both R1 and R2 have two spaces after them instead of one.

**Comment by deviantintegral** [comment]
I think the Chrome xml viewer treats the file like HTML and collapses multiple spaces into 1. See the difference when I look at the xml outside of a browser:

<img width="2560" alt="Image" src="https://github.com/user-attachments/assets/c821db24-5465-4460-a233-e5b8f3f1251c" />

**Comment by RicLund** [comment]
OK yes, I see it if I curl, funnily enough even Postman collapses the spaces in "raw" view.

How often does the HA integration pull the file? I guess that's when mine will stop working.

**Comment by bobstaff** [comment]
I just noticed this error when I noticed that my rates were not changing....

"This entity is no longer being provided by the ontario_energy_board integration. If the entity is no longer in use, delete it in settings."

**Comment by deviantintegral** [comment]
The feed has been fixed again, and they're hoping to fix it in the upstream systems so it sticks.

**Comment by jrfernandes** [comment]
Hydro One seems to have had some issues in the past, but seems to be stable now. Will close this issue as it's out of our control.
